### ISSUE TITLE
Software catalog

### ISSUE THREAD

**Issue by cmd-ntrf** [ulaval-rs/ulaval-rs.github.io#2]
CANARIE is asking the team to catalog institution software and excepts that catalog to be available somewhere. Since, as far as I am aware, there is no institution software catalog, I recommend we add a section to our website that catalogs the software we have found.

Here is a list of software that should figure in that section:
- [ ] Poutyne
- [ ] DEAP
- [ ] MEF++
- [ ] PVABio
- [ ] BEPPO
- [ ] PAX
- [ ] R-Omix
- [ ] VEXOR
- [ ] Bio2RDF
- [ ] rGADEM
- [ ] rMAT
- [ ] rTANDEM
- [ ] ShinnyTandem
- [ ] Metagene
- [ ] Imetagene
- [ ] ENCODExplorer
- [ ] similaRpeak
- [ ] nucleoSim
- [ ] consensusSeekeR
- [ ] RJMCMC
- [ ] ShinySNP
- [ ] methylInheritance
- [ ] LogiLab
- [ ] SilviLab
- [ ] Ray
- [ ] kover
- [ ] PAG
- [ ] Imaris
- [ ] Fiji (ImageJ)
- [ ] PostGIS Raster
- [ ] Lemmatiseur
- [ ] ListIt
- [ ] HOOPLA

For each software, we should provide a small summary of what it is, and a link to its source code / repository if available.

**Comment by gacou54** [comment]
The catalog page is started in this branch: https://github.com/ulaval-rs/ulaval-rs.github.io/tree/docs/catalog.

Any comments on the layout before we fill out the page @cmd-ntrf?
